@ECHO off

REM Set licence to Academic Reaserch Mechanical (no limit)
REM SET ANSYS192_PRODUCT=aa_r_me

REM Set licence to Academic Teaching Mechanical (256K limit)
REM SET ANSYS192_PRODUCT=aa_t_me

REM Set licence to Academic Teaching Introductory (32K limit)
SET ANSYS192_PRODUCT=aa_t_i

REM Disable dialog boxes so that jobs can run consecutively
SET ANS_CONSEC=YES

REM Set ansys executable
SET ANS_EXE="D:\Software\ANSYS Inc\ANSYS Student\v192\ansys\bin\winx64\ANSYS192.exe"
REM SET ANS_EXE="C:\Program Files\ANSYS Inc\v192\ansys\bin\winx64\ANSYS192.exe"

REM Define parameters
SET ANS_NP=2
SET ANS_M=5000
SET ANS_DB=250

REM Define variants
FOR %%P in (85) DO (
	FOR %%L in (0 5 10 15 20) DO (
		REM Print information about current job
		ECHO %date% %time% Ansys pocita vzorek s porozitou %%P%%, ktery ma %%L%% porusenych tramecku, 0%% zaslepenych poru a 0%% shluku materilu
		REM Run the job
		rem %ANS_EXE% -b nolist -np %ANS_NP% -m %ANS_M% -db %ANS_DB% -j dp -i ROUTINE.inp -o dp.out -porosity %%P -pcOfLinesToDelete %%L -pcOfAreasToKeep 0 -pcOfVolumesToKeep 0
		REM Print information about finished job
		ECHO %date% %time% Dopocitano & ECHO:
	)
	FOR %%A in (0 5 10 15) DO (
		REM Print information about current job
		ECHO %date% %time% Ansys pocita vzorek s porozitou %%P%%, ktery ma 0%% porusenych tramecku, %%A%% zaslepenych poru a 0%% shluku materilu
		REM Run the job
		rem %ANS_EXE% -b nolist -np %ANS_NP% -m %ANS_M% -db %ANS_DB% -j dp -i ROUTINE.inp -o dp.out -porosity %%P -pcOfLinesToDelete 0 -pcOfAreasToKeep %%A -pcOfVolumesToKeep 0
		REM Print information about finished job
		ECHO %date% %time% Dopocitano & ECHO:
	)
	FOR %%L in (5 10 15 20) DO (
	FOR %%A in (5 10 15) DO (
	FOR %%V in (0) DO (
		REM Print information about current job
		ECHO %date% %time% Ansys pocita vzorek s porozitou %%P%%, ktery ma %%L%% porusenych tramecku, %%A%% zaslepenych poru a %%V%% shluku materilu
		REM Run the job
		rem %ANS_EXE% -b nolist -np %ANS_NP% -m %ANS_M% -db %ANS_DB% -j dp -i ROUTINE.inp -o dp.out -porosity %%P -pcOfLinesToDelete %%L -pcOfAreasToKeep %%A -pcOfVolumesToKeep %%V
		REM Print information about finished job
		ECHO %date% %time% Dopocitano & ECHO:
	)))
)

REM -p productname
REM Defines which ANSYS product will run during the session.

REM -b list or nolist
REM Activates the Mechanical APDL program in batch mode. The options -b list or -b by itself cause the input listing to be included in the output.

REM -np
REM Specifies the number of processors to use when running Distributed ANSYS or Shared-memory ANSYS.

REM -m workspace
REM Specifies the total size of the workspace (memory) in megabytes used for the initial allocation. If you omit the -m option, the default is 2 GB (2048 MB). Specify a negative number (-value) to force a fixed size throughout the run.

REM -db value
REM Defines the portion of workspace (memory) to be used as the initial allocation for the database. The default is 1024 MB. Specify a negative number (-value) to force a fixed size throughout the run; useful on small memory systems.

REM -j Jobname
REM Specifies the initial jobname, a name assigned to all files generated by the program for a specific model. If you omit the -j option, the jobname is assumed to be file.

REM -i inputname
REM Specifies the name of the file to read input into Mechanical APDL for batch processing. On Linux, the preferred method to indicate an input file is <.

REM -o outputname
REM Specifies the name of the file to store the output from a batch execution of Mechanical APDL. On Linux, the preferred method to indicate an output file is >.

REM Suspends execution of a batch file until a key is pressed.
PAUSE
